### ISSUE TITLE
Error during dev run (MacOS)

### ISSUE THREAD

**Issue by Blucknote** [Fuzzy-Search/chat-with-page#4]
I'm not familiar with JS stack, installed pnpm, activated autoenv (I think) and when i do `pnpm run dev` this happens:
```
> api-local-server@1.0.0 dev /Users/evgen/chat-with-page/api-endpoint
> echo 'running dev server for streaming output ❇️' && node server.js

running dev server for streaming output ❇️
/Users/evgen/chat-with-page/api-endpoint/node_modules/.pnpm/ai@2.2.20_react@18.2.0_solid-js@1.8.5_svelte@4.2.2_vue@3.3.7/node_modules/ai/dist/index.js:482
var StreamingTextResponse = class extends Response {
                            ^

ReferenceError: Response is not defined
    at Object.<anonymous> (/Users/evgen/chat-with-page/api-endpoint/node_modules/.pnpm/ai@2.2.20_react@18.2.0_solid-js@1.8.5_svelte@4.2.2_vue@3.3.7/node_modules/ai/dist/index.js:482:29)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/evgen/chat-with-page/api-endpoint/server.js:4:44)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Lurrobert** [comment]
Hey!

I have just noticed this! Thanks!

try `node api-endpoint/server.js` instead of pnpm run dev

**Comment by Blucknote** [comment]
Still same error
```
 ~/chat-with-page  on main !1  node api-endpoint/server.js                                                                              ✔  at 13:53:56
***@***.******@***.******@***.******@***.******@***.***/node_modules/ai/dist/index.js:482
var StreamingTextResponse = class extends Response {
                            ^

ReferenceError: Response is not defined
    at Object.<anonymous> ***@***.******@***.******@***.******@***.******@***.***/node_modules/ai/dist/index.js:482:29)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/evgen/chat-with-page/api-endpoint/server.js:4:44)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

> 6 нояб. 2023 г., в 03:27, Roberto ***@***.***> написал(а):
> 
> node api-endpoint/server.js

**Comment by Blucknote** [comment]
After investigation I found out that I need to upgrade my nodejs to 18 and after that endpoint looking working.

**Comment by Lurrobert** [comment]
Thanks for replying and closing! 
❤️
